const fs = require('fs');

const questions2 = [
  // ANATOMY (11-20)
  { subject: 'Anatomy', q: 'Which of the following structures is found in the anterior mediastinum?', c1: 'Thymus', c2: 'Esophagus', c3: 'Descending aorta', c4: 'Thoracic duct', ans: 'Thymus', exp: 'The thymus gland (or its remnants in adults) is located in the anterior mediastinum.' },
  { subject: 'Anatomy', q: 'The superficial perineal pouch contains which of the following muscles?', c1: 'Deep transverse perineal muscle', c2: 'Sphincter urethrae', c3: 'Bulbospongiosus', c4: 'Levator ani', ans: 'Bulbospongiosus', exp: 'The bulbospongiosus, ischiocavernosus, and superficial transverse perineal muscles are in the superficial pouch.' },
  { subject: 'Anatomy', q: 'Which cranial nerve is responsible for the afferent limb of the corneal reflex?', c1: 'Oculomotor (CN III)', c2: 'Trigeminal (CN V)', c3: 'Facial (CN VII)', c4: 'Optic (CN II)', ans: 'Trigeminal (CN V)', exp: 'The ophthalmic branch (V1) of the trigeminal nerve senses the stimulus (afferent), while CN VII provides the motor response (efferent).' },
  { subject: 'Anatomy', q: 'The left testicular vein drains directly into which structure?', c1: 'Inferior vena cava', c2: 'Left renal vein', c3: 'Left internal iliac vein', c4: 'Inferior mesenteric vein', ans: 'Left renal vein', exp: 'Unlike the right testicular vein which drains into the IVC, the left drains into the left renal vein at a 90-degree angle.' },
  { subject: 'Anatomy', q: 'Which ligament contains the ovarian vessels?', c1: 'Round ligament of the uterus', c2: 'Broad ligament', c3: 'Suspensory ligament of the ovary', c4: 'Ovarian ligament', ans: 'Suspensory ligament of the ovary', exp: 'The suspensory ligament of the ovary (infundibulopelvic ligament) contains the ovarian artery and vein.' },
  { subject: 'Anatomy', q: 'A lesion in the optic chiasm most commonly produces which visual field defect?', c1: 'Bitemporal hemianopsia', c2: 'Homonymous hemianopsia', c3: 'Right upper quadrantanopsia', c4: 'Central scotoma', ans: 'Bitemporal hemianopsia', exp: 'Compression of the optic chiasm (e.g., pituitary adenoma) affects decussating fibers, causing bitemporal hemianopsia.' },
  { subject: 'Anatomy', q: 'Which muscle is the primary abductor of the vocal folds?', c1: 'Lateral cricoarytenoid', c2: 'Posterior cricoarytenoid', c3: 'Thyroarytenoid', c4: 'Cricothyroid', ans: 'Posterior cricoarytenoid', exp: 'The posterior cricoarytenoid is the only muscle that abducts the vocal cords, opening the airway.' },
  { subject: 'Anatomy', q: 'The great saphenous vein typically drains into which vein?', c1: 'Popliteal vein', c2: 'Femoral vein', c3: 'External iliac vein', c4: 'Small saphenous vein', ans: 'Femoral vein', exp: 'The great saphenous vein empties into the femoral vein at the saphenofemoral junction.' },
  { subject: 'Anatomy', q: 'Which branch of the internal iliac artery supplies the majority of the uterus?', c1: 'Ovarian artery', c2: 'Uterine artery', c3: 'Internal pudendal artery', c4: 'Vaginal artery', ans: 'Uterine artery', exp: 'The uterine artery, a branch of the internal iliac, is the primary blood supply to the uterus.' },
  { subject: 'Anatomy', q: 'In a lumbar puncture, the needle must pass through which ligament just before entering the epidural space?', c1: 'Supraspinous ligament', c2: 'Interspinous ligament', c3: 'Ligamentum flavum', c4: 'Posterior longitudinal ligament', ans: 'Ligamentum flavum', exp: 'The needle pops through the ligamentum flavum to enter the epidural space, then pierces the dura.' },

  // PHYSIOLOGY (11-20)
  { subject: 'Physiology', q: 'What is the effect of parathyroid hormone (PTH) on the kidneys?', c1: 'Increases calcium and phosphate reabsorption', c2: 'Decreases calcium and phosphate reabsorption', c3: 'Increases calcium reabsorption and increases phosphate excretion', c4: 'Decreases calcium reabsorption and increases phosphate excretion', ans: 'Increases calcium reabsorption and increases phosphate excretion', exp: 'PTH raises blood calcium by increasing renal Ca2+ reabsorption and dumping PO4- in the urine.' },
  { subject: 'Physiology', q: 'Which parameter represents the volume of air remaining in the lungs after a maximal exhalation?', c1: 'Functional residual capacity', c2: 'Residual volume', c3: 'Tidal volume', c4: 'Expiratory reserve volume', ans: 'Residual volume', exp: 'Residual volume cannot be exhaled and prevents alveolar collapse.' },
  { subject: 'Physiology', q: 'In the cardiac cycle, the first heart sound (S1) corresponds to:', c1: 'Closure of semilunar valves', c2: 'Closure of atrioventricular valves', c3: 'Opening of atrioventricular valves', c4: 'Rapid ventricular filling', ans: 'Closure of atrioventricular valves', exp: 'S1 marks the beginning of systole when the mitral and tricuspid (AV) valves close.' },
  { subject: 'Physiology', q: 'Which substance is responsible for the maintenance of the resting membrane potential in neurons?', c1: 'Voltage-gated sodium channels', c2: 'Na+/K+ ATPase pump', c3: 'Calcium channels', c4: 'Ligand-gated ion channels', ans: 'Na+/K+ ATPase pump', exp: 'The Na+/K+ pump moves 3 Na+ out and 2 K+ in, maintaining the negative resting potential.' },
  { subject: 'Physiology', q: 'What is the role of surfactant in the lungs?', c1: 'Increases surface tension', c2: 'Decreases lung compliance', c3: 'Decreases surface tension to prevent alveolar collapse', c4: 'Facilitates mucus clearance', ans: 'Decreases surface tension to prevent alveolar collapse', exp: 'Surfactant (DPPC) reduces surface tension, making the lungs easier to inflate (high compliance).' },
  { subject: 'Physiology', q: 'Which gastrointestinal hormone stimulates gallbladder contraction?', c1: 'Secretin', c2: 'Cholecystokinin (CCK)', c3: 'Gastrin', c4: 'Motilin', ans: 'Cholecystokinin (CCK)', exp: 'CCK is released in response to fatty acids and amino acids, stimulating bile release from the gallbladder.' },
  { subject: 'Physiology', q: 'A decrease in blood pressure sensed by the macula densa leads to the release of:', c1: 'Aldosterone', c2: 'Renin', c3: 'Angiotensin II', c4: 'Antidiuretic hormone', ans: 'Renin', exp: 'The macula densa senses low NaCl (due to low BP) and stimulates JG cells to release renin.' },
  { subject: 'Physiology', q: 'Where is antidiuretic hormone (ADH) synthesized?', c1: 'Anterior pituitary', c2: 'Posterior pituitary', c3: 'Hypothalamus', c4: 'Adrenal cortex', ans: 'Hypothalamus', exp: 'ADH is synthesized in the supraoptic nuclei of the hypothalamus and stored in the posterior pituitary.' },
  { subject: 'Physiology', q: 'What is the primary pacemaker of a healthy heart?', c1: 'AV node', c2: 'SA node', c3: 'Bundle of His', c4: 'Purkinje fibers', ans: 'SA node', exp: 'The Sinoatrial (SA) node inherently depolarizes fastest (60-100 bpm), acting as the pacemaker.' },
  { subject: 'Physiology', q: 'Which wave on an ECG represents ventricular repolarization?', c1: 'P wave', c2: 'QRS complex', c3: 'T wave', c4: 'U wave', ans: 'T wave', exp: 'The T wave corresponds to the repolarization of the ventricles.' },

  // PATHOLOGY (11-20)
  { subject: 'Pathology', q: 'A biopsy of a gastric ulcer reveals "signet ring cells". What is the most likely diagnosis?', c1: 'Peptic ulcer disease', c2: 'Gastric lymphoma', c3: 'Diffuse gastric adenocarcinoma', c4: 'GIST', ans: 'Diffuse gastric adenocarcinoma', exp: 'Signet ring cells (mucin-filled cells with a peripheral nucleus) are characteristic of diffuse type gastric cancer.' },
  { subject: 'Pathology', q: 'Which glomerulonephritis presents with a "lumpy-bumpy" appearance on immunofluorescence?', c1: 'IgA nephropathy', c2: 'Goodpasture syndrome', c3: 'Post-streptococcal glomerulonephritis', c4: 'Membranous nephropathy', ans: 'Post-streptococcal glomerulonephritis', exp: 'PSGN features subepithelial immune complex humps giving a lumpy-bumpy granular pattern.' },
  { subject: 'Pathology', q: 'Multiple myeloma is classically associated with which finding on skull X-ray?', c1: 'Cotton wool spots', c2: 'Punched-out lytic lesions', c3: 'Sunburst pattern', c4: 'Codman triangle', ans: 'Punched-out lytic lesions', exp: 'Myeloma cells stimulate osteoclasts, leading to characteristic "punched-out" lytic bone lesions.' },
  { subject: 'Pathology', q: 'A 4-year-old boy presents with progressive muscle weakness and calf pseudohypertrophy. What is the mutated gene?', c1: 'FBN1', c2: 'DMD (Dystrophin)', c3: 'CFTR', c4: 'HTT', ans: 'DMD (Dystrophin)', exp: 'Duchenne muscular dystrophy is an X-linked recessive disorder caused by a frameshift mutation in the dystrophin gene.' },
  { subject: 'Pathology', q: 'What is the hallmark histological finding in Hodgkin lymphoma?', c1: 'Reed-Sternberg cells', c2: 'Auer rods', c3: 'Smudge cells', c4: 'Homer-Wright rosettes', ans: 'Reed-Sternberg cells', exp: 'Reed-Sternberg cells (owl-eye appearance) are diagnostic for Hodgkin lymphoma.' },
  { subject: 'Pathology', q: 'Which type of emphysema is most commonly associated with alpha-1 antitrypsin deficiency?', c1: 'Centriacinar', c2: 'Panacinar', c3: 'Paraseptal', c4: 'Irregular', ans: 'Panacinar', exp: 'Alpha-1 antitrypsin deficiency typically causes panacinar emphysema, predominantly in the lower lobes.' },
  { subject: 'Pathology', q: 'A female patient presents with a solitary, painless, rubbery breast mass. Histology shows proliferation of stroma and glands. Diagnosis?', c1: 'Invasive ductal carcinoma', c2: 'Fibroadenoma', c3: 'Fibrocystic change', c4: 'Phyllodes tumor', ans: 'Fibroadenoma', exp: 'Fibroadenoma is a common benign biphasic tumor (stroma and epithelium) in young women.' },
  { subject: 'Pathology', q: 'Which marker is highly elevated in hepatocellular carcinoma?', c1: 'CA-125', c2: 'PSA', c3: 'Alpha-fetoprotein (AFP)', c4: 'CEA', ans: 'Alpha-fetoprotein (AFP)', exp: 'AFP is the most useful tumor marker for monitoring and diagnosing hepatocellular carcinoma.' },
  { subject: 'Pathology', q: 'What is the characteristic feature of Alzheimer\'s disease on brain biopsy?', c1: 'Lewy bodies', c2: 'Neurofibrillary tangles and amyloid plaques', c3: 'Pick bodies', c4: 'Spongiform encephalopathy', ans: 'Neurofibrillary tangles and amyloid plaques', exp: 'Alzheimer disease is defined by extracellular A-beta amyloid plaques and intracellular tau tangles.' },
  { subject: 'Pathology', q: 'Which sexually transmitted infection is characterized by a painless chancre?', c1: 'Chancroid', c2: 'Herpes simplex', c3: 'Primary syphilis', c4: 'Gonorrhea', ans: 'Primary syphilis', exp: 'Treponema pallidum causes primary syphilis, which presents as a painless ulcer (chancre).' },

  // PHARMACOLOGY (11-20)
  { subject: 'Pharmacology', q: 'Which drug is a specific antagonist for benzodiazepine overdose?', c1: 'Naloxone', c2: 'Flumazenil', c3: 'Protamine', c4: 'Fomepizole', ans: 'Flumazenil', exp: 'Flumazenil competitively inhibits the GABA-A receptor benzodiazepine binding site.' },
  { subject: 'Pharmacology', q: 'A 50-year-old male is prescribed sildenafil. Which class of medications is absolutely contraindicated?', c1: 'Beta-blockers', c2: 'Nitrates', c3: 'Statins', c4: 'Diuretics', ans: 'Nitrates', exp: 'Combining PDE-5 inhibitors (sildenafil) with nitrates causes profound, life-threatening hypotension.' },
  { subject: 'Pharmacology', q: 'Which first-line anti-TB drug is known to cause red-orange discoloration of bodily fluids?', c1: 'Isoniazid', c2: 'Rifampin', c3: 'Pyrazinamide', c4: 'Ethambutol', ans: 'Rifampin', exp: 'Rifampin turns urine, tears, and sweat a harmless red-orange color.' },
  { subject: 'Pharmacology', q: 'What is the primary mechanism of action of omeprazole?', c1: 'H2 receptor antagonist', c2: 'Prostaglandin analog', c3: 'Proton pump inhibitor', c4: 'Antacid', ans: 'Proton pump inhibitor', exp: 'Omeprazole irreversibly inhibits the H+/K+ ATPase (proton pump) in parietal cells.' },
  { subject: 'Pharmacology', q: 'Which antiepileptic drug classically causes gingival hyperplasia?', c1: 'Valproic acid', c2: 'Phenytoin', c3: 'Levetiracetam', c4: 'Carbamazepine', ans: 'Phenytoin', exp: 'Phenytoin can cause gingival hyperplasia, hirsutism, and fetal hydantoin syndrome.' },
  { subject: 'Pharmacology', q: 'Heparin exerts its anticoagulant effect primarily by activating:', c1: 'Plasminogen', c2: 'Antithrombin III', c3: 'Protein C', c4: 'Vitamin K epoxide reductase', ans: 'Antithrombin III', exp: 'Heparin binds to and greatly enhances the activity of Antithrombin III, neutralizing factor Xa and thrombin.' },
  { subject: 'Pharmacology', q: 'Which chemotherapy agent is notorious for causing dose-dependent cardiotoxicity?', c1: 'Cisplatin', c2: 'Vincristine', c3: 'Doxorubicin', c4: 'Bleomycin', ans: 'Doxorubicin', exp: 'Doxorubicin (an anthracycline) causes dilated cardiomyopathy, which is cumulative dose-dependent.' },
  { subject: 'Pharmacology', q: 'A patient with asthma uses an inhaler that causes oral candidiasis (thrush). The drug is most likely:', c1: 'Albuterol', c2: 'Fluticasone', c3: 'Ipratropium', c4: 'Montelukast', ans: 'Fluticasone', exp: 'Inhaled corticosteroids (Fluticasone) can cause local immunosuppression leading to thrush. Rinsing the mouth prevents it.' },
  { subject: 'Pharmacology', q: 'Which antibiotic acts by inhibiting bacterial DNA gyrase?', c1: 'Ciprofloxacin', c2: 'Amoxicillin', c3: 'Azithromycin', c4: 'Doxycycline', ans: 'Ciprofloxacin', exp: 'Fluoroquinolones (like ciprofloxacin) inhibit DNA gyrase (topoisomerase II) and topoisomerase IV.' },
  { subject: 'Pharmacology', q: 'What is the main side effect associated with ACE inhibitors besides cough?', c1: 'Hypokalemia', c2: 'Angioedema', c3: 'Bradycardia', c4: 'Pedal edema', ans: 'Angioedema', exp: 'ACE inhibitors can cause life-threatening angioedema due to elevated bradykinin levels.' },

  // SURGERY (11-20)
  { subject: 'Surgery', q: 'What is the most common location for an anal fissure?', c1: 'Posterior midline', c2: 'Anterior midline', c3: 'Right lateral', c4: 'Left lateral', ans: 'Posterior midline', exp: 'Over 90% of anal fissures occur in the posterior midline due to poor blood supply.' },
  { subject: 'Surgery', q: 'A 60-year-old male presents with painless jaundice and a palpable, non-tender gallbladder (Courvoisier sign). What is the suspected diagnosis?', c1: 'Choledocholithiasis', c2: 'Hepatitis C', c3: 'Pancreatic head carcinoma', c4: 'Primary biliary cholangitis', ans: 'Pancreatic head carcinoma', exp: 'Courvoisier sign strongly suggests a malignant obstruction of the biliary tree, usually pancreatic cancer.' },
  { subject: 'Surgery', q: 'Which physical exam finding is most specific for acute appendicitis?', c1: 'Murphy sign', c2: 'Rovsing sign', c3: 'Cullen sign', c4: 'Kehr sign', ans: 'Rovsing sign', exp: 'Rovsing sign (RLQ pain upon palpation of the LLQ) is highly suggestive of appendicitis.' },
  { subject: 'Surgery', q: 'A patient develops severe abdominal pain out of proportion to physical exam findings. They have a history of atrial fibrillation. Diagnosis?', c1: 'Acute mesenteric ischemia', c2: 'Perforated peptic ulcer', c3: 'Acute pancreatitis', c4: 'Bowel obstruction', ans: 'Acute mesenteric ischemia', exp: 'Pain out of proportion to exam in a patient with an embolus source (A-fib) points to acute mesenteric ischemia.' },
  { subject: 'Surgery', q: 'What is the standard surgical treatment for a localized, early-stage breast cancer?', c1: 'Radical mastectomy', c2: 'Lumpectomy with sentinel lymph node biopsy and radiation', c3: 'Total mastectomy without lymph node biopsy', c4: 'Systemic chemotherapy only', ans: 'Lumpectomy with sentinel lymph node biopsy and radiation', exp: 'Breast-conserving surgery (lumpectomy) with SLNB followed by radiation is the standard of care for early-stage disease.' },
  { subject: 'Surgery', q: 'Which type of shock is most likely in a trauma patient with massive hemorrhage?', c1: 'Cardiogenic', c2: 'Neurogenic', c3: 'Hypovolemic', c4: 'Septic', ans: 'Hypovolemic', exp: 'Massive blood loss causes hypovolemic (hemorrhagic) shock, treated with fluids and blood products.' },
  { subject: 'Surgery', q: 'A patient complains of pain, pulselessness, pallor, paresthesia, and paralysis in the left leg. What is the diagnosis?', c1: 'Deep vein thrombosis', c2: 'Acute arterial occlusion', c3: 'Varicose veins', c4: 'Compartment syndrome', ans: 'Acute arterial occlusion', exp: 'The "5 Ps" are classic signs of acute limb ischemia (arterial occlusion).' },
  { subject: 'Surgery', q: 'What is the most common cause of a mechanical large bowel obstruction?', c1: 'Hernia', c2: 'Adhesions', c3: 'Colorectal cancer', c4: 'Volvulus', ans: 'Colorectal cancer', exp: 'While adhesions cause small bowel obstruction, colorectal cancer is the most common cause of large bowel obstruction.' },
  { subject: 'Surgery', q: 'A trauma patient has Beck\'s triad: hypotension, JVD, and muffled heart sounds. What is the immediate treatment?', c1: 'Chest tube insertion', c2: 'Pericardiocentesis', c3: 'IV fluids', c4: 'Burr hole', ans: 'Pericardiocentesis', exp: 'Beck triad indicates cardiac tamponade, requiring emergent pericardiocentesis.' },
  { subject: 'Surgery', q: 'What is the primary indication for a carotid endarterectomy?', c1: 'Asymptomatic 30% stenosis', c2: 'Symptomatic >70% stenosis', c3: 'Total occlusion of the internal carotid', c4: 'Carotid aneurysm', ans: 'Symptomatic >70% stenosis', exp: 'CEA is highly beneficial for symptomatic patients with high-grade (70-99%) carotid stenosis to prevent stroke.' },

  // INTERNAL MEDICINE (11-20)
  { subject: 'Internal Medicine', q: 'A 25-year-old female has a malar rash, joint pain, and proteinuria. Which lab test is most sensitive for this condition?', c1: 'Anti-dsDNA', c2: 'Anti-Smith', c3: 'ANA (Antinuclear antibody)', c4: 'Rheumatoid factor', ans: 'ANA (Antinuclear antibody)', exp: 'ANA is the most sensitive screening test for SLE (almost 100%), though anti-dsDNA is more specific.' },
  { subject: 'Internal Medicine', q: 'Which pathogen is the most common cause of urinary tract infections?', c1: 'Staphylococcus saprophyticus', c2: 'Escherichia coli', c3: 'Proteus mirabilis', c4: 'Klebsiella pneumoniae', ans: 'Escherichia coli', exp: 'E. coli is responsible for 75-90% of uncomplicated UTIs.' },
  { subject: 'Internal Medicine', q: 'A patient with a history of IV drug use presents with fever, a new heart murmur, and Janeway lesions. Diagnosis?', c1: 'Rheumatic fever', c2: 'Infective endocarditis', c3: 'Myocarditis', c4: 'Pericarditis', ans: 'Infective endocarditis', exp: 'Fever, new murmur, and peripheral stigmata (Janeway lesions, Osler nodes) are classic for endocarditis.' },
  { subject: 'Internal Medicine', q: 'What is the diagnostic test of choice for pulmonary embolism?', c1: 'Chest X-ray', c2: 'D-dimer', c3: 'CT pulmonary angiography (CTPA)', c4: 'Echocardiogram', ans: 'CT pulmonary angiography (CTPA)', exp: 'CTPA is the gold standard and most commonly used imaging test to diagnose a PE.' },
  { subject: 'Internal Medicine', q: 'A 50-year-old male presents with a "fixed, split S2" on cardiac auscultation. What is the congenital defect?', c1: 'Ventricular septal defect', c2: 'Atrial septal defect', c3: 'Tetralogy of Fallot', c4: 'Patent ductus arteriosus', ans: 'Atrial septal defect', exp: 'An ASD classically produces a wide, fixed splitting of the second heart sound (S2).' },
  { subject: 'Internal Medicine', q: 'Which hepatitis virus requires a co-infection with Hepatitis B to replicate?', c1: 'Hepatitis A', c2: 'Hepatitis C', c3: 'Hepatitis D', c4: 'Hepatitis E', ans: 'Hepatitis D', exp: 'Hepatitis D is a defective virus that relies on the HBsAg coat from Hepatitis B to replicate.' },
  { subject: 'Internal Medicine', q: 'A patient presents with polyuria, polydipsia, and a normal blood glucose. Urine specific gravity is low. Diagnosis?', c1: 'Diabetes mellitus', c2: 'Diabetes insipidus', c3: 'Psychogenic polydipsia', c4: 'SIADH', ans: 'Diabetes insipidus', exp: 'DI involves a lack of ADH (or renal resistance), causing copious dilute urine despite normal blood glucose.' },
  { subject: 'Internal Medicine', q: 'Which ECG finding is pathognomonic for Wolff-Parkinson-White (WPW) syndrome?', c1: 'ST elevation', c2: 'Prolonged PR interval', c3: 'Delta wave', c4: 'Peaked T waves', ans: 'Delta wave', exp: 'A short PR interval and a delta wave (slurred QRS upstroke) characterize WPW due to the accessory pathway (Bundle of Kent).' },
  { subject: 'Internal Medicine', q: 'A patient has fatigue, pallor, and a craving for ice (pica). Laboratory tests will likely show:', c1: 'High ferritin, low TIBC', c2: 'Low ferritin, high TIBC', c3: 'Normal ferritin, high TIBC', c4: 'Low ferritin, low TIBC', ans: 'Low ferritin, high TIBC', exp: 'These are signs of iron deficiency anemia, characterized by depleted iron stores (low ferritin) and high transferrin/TIBC.' },
  { subject: 'Internal Medicine', q: 'What is the most effective lifestyle intervention to lower blood pressure?', c1: 'Weight loss', c2: 'DASH diet', c3: 'Sodium restriction', c4: 'Aerobic exercise', ans: 'Weight loss', exp: 'Weight loss produces the most significant reduction in blood pressure among lifestyle modifications.' }
];

let csvContent = fs.readFileSync('public/questions_medical.csv', 'utf-8');

questions2.forEach((q, i) => {
  const escapeCSV = (str) => '"' + String(str).replace(/"/g, '""') + '"';
  csvContent += `Q(${i+61}),${escapeCSV(q.q)},${escapeCSV(q.c1)},${escapeCSV(q.c2)},${escapeCSV(q.c3)},${escapeCSV(q.c4)},${escapeCSV(q.ans)},${escapeCSV(q.exp)},,,${escapeCSV(q.subject)}\n`;
});

fs.writeFileSync('public/questions_medical.csv', csvContent, 'utf-8');
console.log('Successfully appended 60 more questions. Total is now 120!');
