const fs = require('fs');

const questions = [
  // ================== ANATOMY ==================
  { subject: 'Anatomy', q: 'A 25-year-old male sustains a fracture to the surgical neck of the humerus. Which nerve is most likely at risk of injury?', c1: 'Radial nerve', c2: 'Axillary nerve', c3: 'Median nerve', c4: 'Ulnar nerve', ans: 'Axillary nerve', exp: 'The axillary nerve wraps around the surgical neck of the humerus and is highly susceptible to injury in fractures of this region.' },
  { subject: 'Anatomy', q: 'Which of the following muscles is innervated by the thoracodorsal nerve?', c1: 'Trapezius', c2: 'Latissimus dorsi', c3: 'Rhomboid major', c4: 'Levator scapulae', ans: 'Latissimus dorsi', exp: 'The latissimus dorsi is innervated by the thoracodorsal nerve (C6, C7, C8).' },
  { subject: 'Anatomy', q: 'A patient presents with a winged scapula after a radical mastectomy. Which nerve was most likely damaged?', c1: 'Long thoracic nerve', c2: 'Accessory nerve', c3: 'Dorsal scapular nerve', c4: 'Suprascapular nerve', ans: 'Long thoracic nerve', exp: 'Damage to the long thoracic nerve paralyzes the serratus anterior, causing winging of the scapula.' },
  { subject: 'Anatomy', q: 'The recurrent laryngeal nerve is a branch of which cranial nerve?', c1: 'Glossopharyngeal nerve (CN IX)', c2: 'Vagus nerve (CN X)', c3: 'Accessory nerve (CN XI)', c4: 'Hypoglossal nerve (CN XII)', ans: 'Vagus nerve (CN X)', exp: 'The recurrent laryngeal nerve is a branch of the vagus nerve (CN X).' },
  { subject: 'Anatomy', q: 'A 45-year-old woman complains of numbness in the palmar aspect of her lateral three and a half fingers. Which nerve is compressed?', c1: 'Radial nerve', c2: 'Median nerve', c3: 'Ulnar nerve', c4: 'Musculocutaneous nerve', ans: 'Median nerve', exp: 'Carpal tunnel syndrome involves compression of the median nerve, affecting the lateral 3.5 digits.' },
  { subject: 'Anatomy', q: 'Which coronary artery typically supplies the AV node in right-dominant individuals?', c1: 'Left anterior descending (LAD)', c2: 'Left circumflex (LCx)', c3: 'Right coronary artery (RCA)', c4: 'Obtuse marginal artery', ans: 'Right coronary artery (RCA)', exp: 'In right-dominant hearts, the RCA supplies the AV nodal artery.' },
  { subject: 'Anatomy', q: 'The portal vein is formed by the union of which two veins?', c1: 'Superior mesenteric and splenic veins', c2: 'Inferior mesenteric and splenic veins', c3: 'Superior and inferior mesenteric veins', c4: 'Hepatic veins and inferior vena cava', ans: 'Superior mesenteric and splenic veins', exp: 'The portal vein is formed by the confluence of the superior mesenteric vein and the splenic vein.' },
  { subject: 'Anatomy', q: 'Which structure passes through the foramen spinosum?', c1: 'Mandibular nerve (V3)', c2: 'Middle meningeal artery', c3: 'Internal carotid artery', c4: 'Maxillary nerve (V2)', ans: 'Middle meningeal artery', exp: 'The middle meningeal artery passes through the foramen spinosum.' },
  { subject: 'Anatomy', q: 'A 60-year-old male has difficulty extending his knee. Which nerve is most likely compromised?', c1: 'Sciatic nerve', c2: 'Obturator nerve', c3: 'Femoral nerve', c4: 'Tibial nerve', ans: 'Femoral nerve', exp: 'The femoral nerve innervates the quadriceps femoris, which extends the knee.' },
  { subject: 'Anatomy', q: 'Where is the primary visual cortex located?', c1: 'Frontal lobe', c2: 'Parietal lobe', c3: 'Temporal lobe', c4: 'Occipital lobe', ans: 'Occipital lobe', exp: 'The primary visual cortex is located in the occipital lobe at the calcarine fissure.' },
  
  // ================== PHYSIOLOGY ==================
  { subject: 'Physiology', q: 'Which hormone is primarily responsible for the let-down reflex during lactation?', c1: 'Prolactin', c2: 'Oxytocin', c3: 'Estrogen', c4: 'Progesterone', ans: 'Oxytocin', exp: 'Oxytocin stimulates myoepithelial cells in the breast, causing milk ejection or the "let-down" reflex.' },
  { subject: 'Physiology', q: 'What is the primary driver for respiration in a healthy individual?', c1: 'Low PO2', c2: 'High PCO2', c3: 'High PO2', c4: 'Low blood pH only', ans: 'High PCO2', exp: 'Central chemoreceptors are highly sensitive to changes in arterial PCO2 (via H+ in CSF), which is the primary driver of ventilation.' },
  { subject: 'Physiology', q: 'Which part of the nephron reabsorbs the largest percentage of filtered sodium?', c1: 'Proximal convoluted tubule', c2: 'Loop of Henle', c3: 'Distal convoluted tubule', c4: 'Collecting duct', ans: 'Proximal convoluted tubule', exp: 'The PCT reabsorbs about 65-70% of filtered sodium and water.' },
  { subject: 'Physiology', q: 'A rightward shift of the oxygen-hemoglobin dissociation curve can be caused by:', c1: 'Decreased temperature', c2: 'Increased pH', c3: 'Increased 2,3-BPG', c4: 'Decreased PCO2', ans: 'Increased 2,3-BPG', exp: 'Increased 2,3-BPG, high temperature, high PCO2, and low pH cause a rightward shift, facilitating O2 unloading.' },
  { subject: 'Physiology', q: 'Which phase of the cardiac action potential in ventricular muscle is characterized by calcium influx?', c1: 'Phase 0', c2: 'Phase 1', c3: 'Phase 2 (Plateau)', c4: 'Phase 3', ans: 'Phase 2 (Plateau)', exp: 'Phase 2 is the plateau phase, driven by the inward flow of calcium ions through L-type Ca2+ channels.' },
  { subject: 'Physiology', q: 'In the stomach, parietal cells secrete HCl and which other important substance?', c1: 'Pepsinogen', c2: 'Gastrin', c3: 'Intrinsic factor', c4: 'Mucus', ans: 'Intrinsic factor', exp: 'Parietal cells secrete HCl and intrinsic factor, which is essential for vitamin B12 absorption.' },
  { subject: 'Physiology', q: 'Which hormone decreases blood glucose levels by promoting cellular uptake?', c1: 'Glucagon', c2: 'Epinephrine', c3: 'Cortisol', c4: 'Insulin', ans: 'Insulin', exp: 'Insulin is the primary anabolic hormone that lowers blood glucose.' },
  { subject: 'Physiology', q: 'What is the main physiological role of aldosterone?', c1: 'Increase sodium excretion', c2: 'Increase potassium reabsorption', c3: 'Increase sodium reabsorption and potassium excretion', c4: 'Decrease water reabsorption', ans: 'Increase sodium reabsorption and potassium excretion', exp: 'Aldosterone acts on the principal cells of the collecting duct to increase Na+ reabsorption and K+ secretion.' },
  { subject: 'Physiology', q: 'Which clotting factor is activated by the intrinsic pathway but not the extrinsic pathway?', c1: 'Factor VII', c2: 'Factor XII', c3: 'Factor X', c4: 'Factor II (Prothrombin)', ans: 'Factor XII', exp: 'Factor XII (Hageman factor) initiates the intrinsic coagulation cascade.' },
  { subject: 'Physiology', q: 'Where does the greatest vascular resistance occur in the systemic circulation?', c1: 'Aorta', c2: 'Arterioles', c3: 'Capillaries', c4: 'Veins', ans: 'Arterioles', exp: 'Arterioles are the major resistance vessels in the systemic circulation.' },

  // ================== PATHOLOGY ==================
  { subject: 'Pathology', q: 'A 60-year-old smoker presents with hemoptysis and weight loss. Biopsy shows keratin pearls and intercellular bridges. Diagnosis?', c1: 'Small cell carcinoma', c2: 'Squamous cell carcinoma', c3: 'Adenocarcinoma', c4: 'Large cell carcinoma', ans: 'Squamous cell carcinoma', exp: 'Keratin pearls and intercellular bridges are histological hallmarks of squamous cell carcinoma of the lung.' },
  { subject: 'Pathology', q: 'Which type of necrosis is classically associated with tuberculosis?', c1: 'Coagulative necrosis', c2: 'Liquefactive necrosis', c3: 'Caseous necrosis', c4: 'Fat necrosis', ans: 'Caseous necrosis', exp: 'Caseous necrosis is typical for granulomatous inflammation seen in tuberculosis.' },
  { subject: 'Pathology', q: 'A Philadelphia chromosome (t(9;22)) is most commonly associated with which leukemia?', c1: 'ALL', c2: 'CLL', c3: 'AML', c4: 'CML', ans: 'CML', exp: 'Chronic Myeloid Leukemia (CML) is characterized by the BCR-ABL fusion gene from t(9;22).' },
  { subject: 'Pathology', q: 'Which autoimmune disease is characterized by anti-dsDNA and anti-Sm antibodies?', c1: 'Rheumatoid arthritis', c2: 'Sjögren syndrome', c3: 'Systemic lupus erythematosus (SLE)', c4: 'Systemic sclerosis', ans: 'Systemic lupus erythematosus (SLE)', exp: 'Anti-dsDNA and anti-Smith antibodies are highly specific for SLE.' },
  { subject: 'Pathology', q: 'A patient has a "starry sky" appearance on lymph node biopsy. What is the diagnosis?', c1: 'Hodgkin lymphoma', c2: 'Burkitt lymphoma', c3: 'Follicular lymphoma', c4: 'Mantle cell lymphoma', ans: 'Burkitt lymphoma', exp: 'Burkitt lymphoma histologically shows a "starry sky" pattern due to macrophages interspersed among rapidly dividing tumor cells.' },
  { subject: 'Pathology', q: 'What is the most common cause of right-sided heart failure?', c1: 'Pulmonary hypertension', c2: 'Right ventricular infarction', c3: 'Left-sided heart failure', c4: 'Tricuspid regurgitation', ans: 'Left-sided heart failure', exp: 'Left-sided heart failure leads to pulmonary congestion, eventually causing right-sided heart failure.' },
  { subject: 'Pathology', q: 'Which inflammatory bowel disease is characterized by skip lesions and transmural inflammation?', c1: 'Ulcerative colitis', c2: 'Crohn disease', c3: 'Celiac disease', c4: 'Microscopic colitis', ans: 'Crohn disease', exp: 'Crohn disease features transmural inflammation and non-contiguous "skip" lesions anywhere in the GI tract.' },
  { subject: 'Pathology', q: 'A patient with chronic alcoholism presents with ascites, jaundice, and caput medusae. Liver biopsy would show:', c1: 'Macrovesicular steatosis and fibrosis', c2: 'Massive necrosis', c3: 'Granulomas', c4: 'Amyloid deposition', ans: 'Macrovesicular steatosis and fibrosis', exp: 'Cirrhosis due to alcohol presents with fibrosis and regenerative nodules, often with underlying macrovesicular steatosis.' },
  { subject: 'Pathology', q: 'Which gene mutation is most strongly associated with familial breast and ovarian cancer?', c1: 'APC', c2: 'p53', c3: 'BRCA1', c4: 'RET', ans: 'BRCA1', exp: 'BRCA1 and BRCA2 mutations significantly increase the risk of breast and ovarian cancers.' },
  { subject: 'Pathology', q: 'Negri bodies in the cytoplasm of neurons are pathognomonic for which viral infection?', c1: 'Herpes simplex virus', c2: 'Rabies virus', c3: 'Cytomegalovirus', c4: 'Poliovirus', ans: 'Rabies virus', exp: 'Negri bodies are eosinophilic cytoplasmic inclusions found in rabies infection.' },

  // ================== PHARMACOLOGY ==================
  { subject: 'Pharmacology', q: 'Which diuretic acts on the thick ascending limb of the loop of Henle?', c1: 'Hydrochlorothiazide', c2: 'Furosemide', c3: 'Spironolactone', c4: 'Acetazolamide', ans: 'Furosemide', exp: 'Loop diuretics like furosemide inhibit the Na-K-2Cl cotransporter in the thick ascending limb.' },
  { subject: 'Pharmacology', q: 'What is the primary mechanism of action of statins?', c1: 'Inhibition of HMG-CoA reductase', c2: 'Binding of bile acids', c3: 'Activation of PPAR-alpha', c4: 'Inhibition of cholesterol absorption', ans: 'Inhibition of HMG-CoA reductase', exp: 'Statins inhibit HMG-CoA reductase, the rate-limiting enzyme in hepatic cholesterol synthesis.' },
  { subject: 'Pharmacology', q: 'Which antibiotic is known to cause "Red Man Syndrome" if infused too rapidly?', c1: 'Penicillin', c2: 'Azithromycin', c3: 'Vancomycin', c4: 'Ciprofloxacin', ans: 'Vancomycin', exp: 'Rapid infusion of Vancomycin causes histamine release, leading to Red Man Syndrome.' },
  { subject: 'Pharmacology', q: 'A patient on warfarin requires emergency reversal of anticoagulation due to severe bleeding. What is the appropriate treatment?', c1: 'Protamine sulfate', c2: 'Vitamin K and Fresh Frozen Plasma (FFP)', c3: 'Idarucizumab', c4: 'Desmopressin', ans: 'Vitamin K and Fresh Frozen Plasma (FFP)', exp: 'FFP provides immediate clotting factors, while Vitamin K allows the liver to synthesize new factors over time.' },
  { subject: 'Pharmacology', q: 'Which class of antihypertensives is associated with a dry, non-productive cough?', c1: 'Calcium channel blockers', c2: 'Beta-blockers', c3: 'ACE inhibitors', c4: 'ARBs', ans: 'ACE inhibitors', exp: 'ACE inhibitors prevent the breakdown of bradykinin, which accumulates and causes a dry cough.' },
  { subject: 'Pharmacology', q: 'Which drug is a selective serotonin reuptake inhibitor (SSRI)?', c1: 'Amitriptyline', c2: 'Fluoxetine', c3: 'Venlafaxine', c4: 'Phenelzine', ans: 'Fluoxetine', exp: 'Fluoxetine is a classic SSRI used for depression and anxiety.' },
  { subject: 'Pharmacology', q: 'What is the antidote for acetaminophen (paracetamol) toxicity?', c1: 'Naloxone', c2: 'Flumazenil', c3: 'N-acetylcysteine (NAC)', c4: 'Atropine', ans: 'N-acetylcysteine (NAC)', exp: 'NAC replenishes glutathione stores in the liver to detoxify the NAPQI metabolite.' },
  { subject: 'Pharmacology', q: 'Which receptor does salbutamol (albuterol) primarily agonize to cause bronchodilation?', c1: 'Alpha-1', c2: 'Alpha-2', c3: 'Beta-1', c4: 'Beta-2', ans: 'Beta-2', exp: 'Albuterol is a short-acting beta-2 adrenergic agonist.' },
  { subject: 'Pharmacology', q: 'Which antidiabetic medication commonly causes lactic acidosis in patients with renal impairment?', c1: 'Glipizide', c2: 'Metformin', c3: 'Pioglitazone', c4: 'Sitagliptin', ans: 'Metformin', exp: 'Metformin is contraindicated in severe renal failure due to the risk of lactic acidosis.' },
  { subject: 'Pharmacology', q: 'Clopidogrel prevents platelet aggregation by blocking which receptor?', c1: 'Glycoprotein IIb/IIIa', c2: 'Thromboxane A2', c3: 'P2Y12 (ADP) receptor', c4: 'PAR-1', ans: 'P2Y12 (ADP) receptor', exp: 'Clopidogrel is an ADP receptor (P2Y12) antagonist.' },

  // ================== SURGERY ==================
  { subject: 'Surgery', q: 'A 24-year-old male presents with periumbilical pain radiating to the right lower quadrant, fever, and nausea. What is the most likely diagnosis?', c1: 'Acute cholecystitis', c2: 'Acute appendicitis', c3: 'Diverticulitis', c4: 'Peptic ulcer disease', ans: 'Acute appendicitis', exp: 'Classic presentation of acute appendicitis starts with periumbilical pain that localizes to the RLQ (McBurney point).' },
  { subject: 'Surgery', q: 'What is the most common cause of small bowel obstruction in adults?', c1: 'Hernias', c2: 'Postoperative adhesions', c3: 'Tumors', c4: 'Volvulus', ans: 'Postoperative adhesions', exp: 'Adhesions from prior abdominal surgeries are the leading cause of SBO.' },
  { subject: 'Surgery', q: 'Charcot\'s triad (fever, jaundice, RUQ pain) is indicative of:', c1: 'Acute pancreatitis', c2: 'Acute cholecystitis', c3: 'Acute cholangitis', c4: 'Hepatic abscess', ans: 'Acute cholangitis', exp: 'Charcot triad suggests acute ascending cholangitis (infection of the biliary tract).' },
  { subject: 'Surgery', q: 'A 65-year-old male smoker presents with a pulsatile abdominal mass. What is the next best step in diagnosis?', c1: 'CT angiogram', c2: 'Abdominal ultrasound', c3: 'MRI abdomen', c4: 'Exploratory laparotomy', ans: 'Abdominal ultrasound', exp: 'Ultrasound is the best initial test to diagnose and measure an abdominal aortic aneurysm (AAA).' },
  { subject: 'Surgery', q: 'What is the most common breast benign tumor in young women?', c1: 'Fibroadenoma', c2: 'Intraductal papilloma', c3: 'Phyllodes tumor', c4: 'Ductal carcinoma in situ', ans: 'Fibroadenoma', exp: 'Fibroadenomas are solid, mobile, benign breast masses common in women under 30.' },
  { subject: 'Surgery', q: 'Which type of hernia passes through the deep inguinal ring?', c1: 'Direct inguinal hernia', c2: 'Indirect inguinal hernia', c3: 'Femoral hernia', c4: 'Spigelian hernia', ans: 'Indirect inguinal hernia', exp: 'Indirect inguinal hernias pass through the deep inguinal ring lateral to the inferior epigastric vessels.' },
  { subject: 'Surgery', q: 'A patient sustains a head injury and experiences a lucid interval followed by rapid deterioration. CT shows a biconvex (lens-shaped) hyperdensity. Diagnosis?', c1: 'Subdural hematoma', c2: 'Subarachnoid hemorrhage', c3: 'Epidural hematoma', c4: 'Intracerebral hemorrhage', ans: 'Epidural hematoma', exp: 'Epidural hematomas (typically from middle meningeal artery rupture) present with a lucid interval and lens-shaped CT appearance.' },
  { subject: 'Surgery', q: 'The "rule of nines" is used to estimate the body surface area involved in:', c1: 'Skin cancer', c2: 'Burns', c3: 'Psoriasis', c4: 'Necrotizing fasciitis', ans: 'Burns', exp: 'The rule of nines quickly estimates the total body surface area (TBSA) affected by burn injuries.' },
  { subject: 'Surgery', q: 'What is the most definitive treatment for a tension pneumothorax before inserting a chest tube?', c1: 'Intubation', c2: 'Needle decompression', c3: 'Oxygen via non-rebreather', c4: 'Pericardiocentesis', ans: 'Needle decompression', exp: 'Immediate needle thoracostomy in the 2nd intercostal space midclavicular line is required to relieve a tension pneumothorax.' },
  { subject: 'Surgery', q: 'A 50-year-old presents with painless hematuria. What is the most likely diagnosis until proven otherwise?', c1: 'Nephrolithiasis', c2: 'Urinary tract infection', c3: 'Bladder cancer', c4: 'Benign prostatic hyperplasia', ans: 'Bladder cancer', exp: 'Painless gross hematuria in adults should raise high suspicion for urothelial (bladder) cancer.' },

  // ================== INTERNAL MEDICINE ==================
  { subject: 'Internal Medicine', q: 'A 45-year-old male presents with acute onset of severe, monoarticular joint pain in his big toe. Joint aspiration shows negatively birefringent needle-shaped crystals. Diagnosis?', c1: 'Pseudogout', c2: 'Gout', c3: 'Rheumatoid arthritis', c4: 'Septic arthritis', ans: 'Gout', exp: 'Monosodium urate crystals in gout are needle-shaped and negatively birefringent under polarized light.' },
  { subject: 'Internal Medicine', q: 'Which blood test is most specific for diagnosing a myocardial infarction?', c1: 'Myoglobin', c2: 'CK-MB', c3: 'Cardiac Troponin I or T', c4: 'LDH', ans: 'Cardiac Troponin I or T', exp: 'Cardiac troponins are highly sensitive and specific biomarkers for myocardial necrosis.' },
  { subject: 'Internal Medicine', q: 'A 30-year-old female presents with episodic wheezing, cough, and shortness of breath that worsens at night. PFTs show reversible airway obstruction. Diagnosis?', c1: 'COPD', c2: 'Asthma', c3: 'Bronchiectasis', c4: 'Pulmonary embolism', ans: 'Asthma', exp: 'Reversible airflow obstruction and episodic wheezing are the hallmarks of asthma.' },
  { subject: 'Internal Medicine', q: 'What is the most common cause of community-acquired pneumonia?', c1: 'Staphylococcus aureus', c2: 'Streptococcus pneumoniae', c3: 'Klebsiella pneumoniae', c4: 'Mycoplasma pneumoniae', ans: 'Streptococcus pneumoniae', exp: 'S. pneumoniae (Pneumococcus) is the leading cause of typical community-acquired pneumonia.' },
  { subject: 'Internal Medicine', q: 'A patient with atrial fibrillation is at highest risk for which complication?', c1: 'Pulmonary embolism', c2: 'Myocardial infarction', c3: 'Ischemic stroke', c4: 'Aortic dissection', ans: 'Ischemic stroke', exp: 'A-fib causes blood stasis in the left atrial appendage, leading to clots that can embolize to the brain.' },
  { subject: 'Internal Medicine', q: 'Which finding is diagnostic for diabetes mellitus?', c1: 'Fasting plasma glucose = 110 mg/dL', c2: 'HbA1c = 6.0%', c3: 'Random plasma glucose = 220 mg/dL with symptoms', c4: '2-hour OGTT = 180 mg/dL', ans: 'Random plasma glucose = 220 mg/dL with symptoms', exp: 'Random glucose ≥ 200 mg/dL with classic symptoms (polyuria, polydipsia) is diagnostic for diabetes.' },
  { subject: 'Internal Medicine', q: 'A 65-year-old male presents with resting tremor, bradykinesia, rigidity, and postural instability. What neurotransmitter is deficient?', c1: 'Serotonin', c2: 'Acetylcholine', c3: 'GABA', c4: 'Dopamine', ans: 'Dopamine', exp: 'Parkinson\'s disease is caused by the degeneration of dopaminergic neurons in the substantia nigra.' },
  { subject: 'Internal Medicine', q: 'What is the first-line treatment for uncomplicated Helicobacter pylori infection?', c1: 'Amoxicillin + Clarithromycin + PPI (Triple therapy)', c2: 'Metronidazole + Tetracycline + PPI', c3: 'Ciprofloxacin + PPI', c4: 'Bismuth alone', ans: 'Amoxicillin + Clarithromycin + PPI (Triple therapy)', exp: 'Standard triple therapy for H. pylori consists of a PPI, clarithromycin, and amoxicillin (or metronidazole).' },
  { subject: 'Internal Medicine', q: 'A patient presents with hyperpigmentation, fatigue, hypotension, and hyponatremia. Cortisol levels are low and ACTH is high. Diagnosis?', c1: 'Cushing syndrome', c2: 'Addison disease', c3: 'Conn syndrome', c4: 'Pheochromocytoma', ans: 'Addison disease', exp: 'Primary adrenal insufficiency (Addison disease) presents with low cortisol, high ACTH (causing hyperpigmentation), and hyponatremia.' },
  { subject: 'Internal Medicine', q: 'Which anemia is characterized by a high Mean Corpuscular Volume (MCV) > 100 fL and hypersegmented neutrophils?', c1: 'Iron deficiency anemia', c2: 'Thalassemia', c3: 'Megaloblastic anemia', c4: 'Aplastic anemia', ans: 'Megaloblastic anemia', exp: 'Vitamin B12 or Folate deficiency causes megaloblastic anemia with macrocytic RBCs and hypersegmented neutrophils.' }
];

let csvContent = 'Q(1): السؤال,خيار 1,خيار 2,خيار 3,خيار 4,الإجابة,التفسير,رابط الصورة,اسم الملف,شرح كامل,العمود 11\n';

questions.forEach((q, i) => {
  const escapeCSV = (str) => '"' + String(str).replace(/"/g, '""') + '"';
  csvContent += `Q(${i+1}),${escapeCSV(q.q)},${escapeCSV(q.c1)},${escapeCSV(q.c2)},${escapeCSV(q.c3)},${escapeCSV(q.c4)},${escapeCSV(q.ans)},${escapeCSV(q.exp)},,,${escapeCSV(q.subject)}\n`;
});

fs.writeFileSync('public/questions_medical.csv', csvContent, 'utf-8');
console.log('Successfully generated questions_medical.csv with 60 questions!');
